const users = [
    { name: "Alice Smith", username: "asmith", email: "alice.smith@example.com" },
    { name: "Bob Johnson", username: "bjohnson", email: "bob.johnson@example.com" },
    { name: "Charlie Brown", username: "cbrown", email: "charlie.brown@example.com" },
    { name: "Diana White", username: "dwhite", email: "diana.white@example.com" },
    { name: "Ethan Black", username: "eblack", email: "ethan.black@example.com" },
    { name: "Fiona Green", username: "fgreen", email: "fiona.green@example.com" },
    { name: "George Harris", username: "gharris", email: "george.harris@example.com" },
    { name: "Hannah Moore", username: "hmoore", email: "hannah.moore@example.com" },
    { name: "Ian Clark", username: "iclark", email: "ian.clark@example.com" },
    { name: "Jasmine Lewis", username: "jlewis", email: "jasmine.lewis@example.com" },
    { name: "Kevin Walker", username: "kwalker", email: "kevin.walker@example.com" },
    { name: "Laura Hall", username: "lhall", email: "laura.hall@example.com" },
    { name: "Michael Young", username: "myoung", email: "michael.young@example.com" },
    { name: "Natalie King", username: "nking", email: "natalie.king@example.com" },
    { name: "Oliver Wright", username: "owright", email: "oliver.wright@example.com" },
    { name: "Paul Scott", username: "pscott", email: "paul.scott@example.com" },
    { name: "Quincy Adams", username: "qadams", email: "quincy.adams@example.com" },
    { name: "Rachel Perez", username: "rperez", email: "rachel.perez@example.com" },
    { name: "Samuel Collins", username: "scollins", email: "samuel.collins@example.com" },
    { name: "Tina Stewart", username: "tstewart", email: "tina.stewart@example.com" },
    { name: "Uma Edwards", username: "uedwards", email: "uma.edwards@example.com" },
    { name: "Victor Martinez", username: "vmartinez", email: "victor.martinez@example.com" },
    { name: "Wendy Thompson", username: "wthompson", email: "wendy.thompson@example.com" },
    { name: "Xander Anderson", username: "xanderson", email: "xander.anderson@example.com" },
    { name: "Yara Taylor", username: "ytaylor", email: "yara.taylor@example.com" },
    { name: "Zachary Wilson", username: "zwilson", email: "zachary.wilson@example.com" },
    { name: "Amy Cooper", username: "acooper", email: "amy.cooper@example.com" },
    { name: "Brian Baker", username: "bbaker", email: "brian.baker@example.com" },
    { name: "Claire Carter", username: "ccarter", email: "claire.carter@example.com" },
    { name: "David Rogers", username: "drogers", email: "david.rogers@example.com" },
    { name: "Ella Powell", username: "epowell", email: "ella.powell@example.com" },
    { name: "Frank Murphy", username: "fmurphy", email: "frank.murphy@example.com" },
    { name: "Grace Torres", username: "gtorres", email: "grace.torres@example.com" },
    { name: "Henry Flores", username: "hflores", email: "henry.flores@example.com" },
]

export default users